version: '3'
services:
  app:
    image: pygeoapitest
    build: .
    ports:
      - "5000:5000"
    environment:
      
      - CONTAINER_PORT=5000
      - inputDir=C:/Daten/Inputs
      - ouputDir=C:/Daten/Results
      - MAX_REQUESTS=100
      - LOG_LEVEL=INFO
    volumes:
      - C:/Daten/Results:/pygeoapi/results
      - C:/Daten/Inputs:/pygeoapi/inputs
      - type: bind 
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
      
